//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yahoo_Finance_Crawler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanceCrawlerEntities : DbContext
    {
        public FinanceCrawlerEntities()
            : base("name=FinanceCrawlerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<YahooFinance_Analyst_Opinion> YahooFinance_Analyst_Opinion { get; set; }
        public DbSet<YahooFinance_Analyst_Estimates> YahooFinance_Analyst_Estimates { get; set; }
        public DbSet<YahooFinance_Market_Data> YahooFinance_Market_Data { get; set; }
    }
}
