//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yahoo_Finance_Crawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class YahooFinance_Analyst_Estimates
    {
        public long Identity { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Recorded_Date { get; set; }
        public Nullable<System.DateTime> Current_Qtr { get; set; }
        public Nullable<System.DateTime> Next_Qtr { get; set; }
        public Nullable<System.DateTime> Current_Year { get; set; }
        public Nullable<System.DateTime> Next_Year { get; set; }
        public Nullable<decimal> Earning_Est_Current_Year_Avg_Estimate { get; set; }
        public Nullable<decimal> Earning_Est_Next_Year_Avg_Estimate { get; set; }
        public Nullable<decimal> Earning_Est_Current_Year_Year_Ago_EPS { get; set; }
        public Nullable<decimal> Earning_Est_Next_Year_Year_Ago_EPS { get; set; }
        public Nullable<decimal> Revenue_Est_Current_Year_Avg_Estimate { get; set; }
        public Nullable<decimal> Revenue_Est_Next_Year_Avg_Estimate { get; set; }
        public Nullable<decimal> Revenue_Est_Current_Year_Year_Ago_Sales { get; set; }
        public Nullable<decimal> Revenue_Est_Next_Year_Year_Ago_Sales { get; set; }
        public Nullable<decimal> Earnings_History_Current_Year_EPS_Est { get; set; }
        public Nullable<decimal> Earnings_History_Next_Year_EPS_Est { get; set; }
        public Nullable<decimal> Earnings_History_Current_Year_EPS_Actual { get; set; }
        public Nullable<decimal> Earnings_History_Next_Year_EPS_Actual { get; set; }
        public Nullable<decimal> Earnings_History_Current_Year_Difference { get; set; }
        public Nullable<decimal> Earnings_History_Next_Year_Difference { get; set; }
        public Nullable<decimal> Earnings_History_Current_Year_Surprise___ { get; set; }
        public Nullable<decimal> Earnings_History_Next_Year_Surprise___ { get; set; }
        public Nullable<decimal> Growth_Est_Company_Current_Qtr___ { get; set; }
        public Nullable<decimal> Growth_Est_Industry_Current_Qtr___ { get; set; }
        public Nullable<decimal> Growth_Est_Sector_Current_Qtr___ { get; set; }
        public Nullable<decimal> Growth_Est_S_P500_Current_Qtr___ { get; set; }
        public Nullable<decimal> Growth_Est_Company_Next_Qtr___ { get; set; }
        public Nullable<decimal> Growth_Est_Industry_Next_Qtr___ { get; set; }
        public Nullable<decimal> Growth_Est_Sector_Next_Qtr___ { get; set; }
        public Nullable<decimal> Growth_Est_S_P500_Next_Qtr___ { get; set; }
        public Nullable<decimal> Growth_Est_Company_This_Year___ { get; set; }
        public Nullable<decimal> Growth_Est_Industry_This_Year___ { get; set; }
        public Nullable<decimal> Growth_Est_Sector_This_Year___ { get; set; }
        public Nullable<decimal> Growth_Est_S_P500_This_Year___ { get; set; }
        public Nullable<decimal> Growth_Est_Company_Next_Year___ { get; set; }
        public Nullable<decimal> Growth_Est_Industry_Next_Year___ { get; set; }
        public Nullable<decimal> Growth_Est_Sector_Next_Year___ { get; set; }
        public Nullable<decimal> Growth_Est_S_P500_Next_Year___ { get; set; }
        public Nullable<decimal> Growth_Est_Company_Past5Years___ { get; set; }
        public Nullable<decimal> Growth_Est_Industry_Past5Years___ { get; set; }
        public Nullable<decimal> Growth_Est_Sector_Past5Years___ { get; set; }
        public Nullable<decimal> Growth_Est_S_P500_Past5Years___ { get; set; }
        public Nullable<decimal> Growth_Est_Company_Next5Years___ { get; set; }
        public Nullable<decimal> Growth_Est_Industry_Next5Years___ { get; set; }
        public Nullable<decimal> Growth_Est_Sector_Next5Years___ { get; set; }
        public Nullable<decimal> Growth_Est_S_P500_Next5Years___ { get; set; }
        public Nullable<decimal> Growth_Est_Company_PriceEarnings { get; set; }
        public Nullable<decimal> Growth_Est_Industry_PriceEarnings { get; set; }
        public Nullable<decimal> Growth_Est_Sector_PriceEarnings { get; set; }
        public Nullable<decimal> Growth_Est_S_P500_PriceEarnings { get; set; }
        public Nullable<decimal> Growth_Est_Company_PEGRatio { get; set; }
        public Nullable<decimal> Growth_Est_Industry_PEGRatio { get; set; }
        public Nullable<decimal> Growth_Est_Sector_PEGRatio { get; set; }
        public Nullable<decimal> Growth_Est_S_P500_PEGRatio { get; set; }
        public string Group { get; set; }
    }
}
