//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yahoo_Finance_Crawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class YahooFinance_Market_Data
    {
        public long Identity { get; set; }
        public string Name { get; set; }
        public System.DateTime Recorded_Date { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Low_Price { get; set; }
        public Nullable<decimal> High_Price { get; set; }
        public Nullable<decimal> C52wk_Low { get; set; }
        public Nullable<decimal> C52wk_High { get; set; }
        public Nullable<decimal> C52wk_Avg { get; set; }
        public Nullable<long> Volume { get; set; }
        public Nullable<long> Avg_Vol_3m_ { get; set; }
        public string Beta { get; set; }
        public Nullable<decimal> Market_Cap_b_ { get; set; }
        public Nullable<decimal> P_E_ttm_ { get; set; }
        public Nullable<decimal> EPS_ttm_ { get; set; }
        public string Group { get; set; }
    }
}
