//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yahoo_Finance_Crawler
{
    using System;
    using System.Collections.Generic;
    
    public partial class YahooFinance_Analyst_Opinion
    {
        public long Identity { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Recomm_ThisWeek { get; set; }
        public Nullable<decimal> Recomm_LastWeek { get; set; }
        public Nullable<decimal> Mean_Target { get; set; }
        public Nullable<decimal> Median_Target { get; set; }
        public Nullable<decimal> High_Target { get; set; }
        public Nullable<decimal> Low_Target { get; set; }
        public Nullable<long> No_of_Brokers { get; set; }
        public Nullable<decimal> CurrentMonth_Strong_Buy { get; set; }
        public Nullable<decimal> LastMonth_Strong_Buy { get; set; }
        public Nullable<decimal> TwoMonthsAgo_Strong_Buy { get; set; }
        public Nullable<decimal> ThreeMonthsAgo_Strong_Buy { get; set; }
        public Nullable<decimal> CurrentMonth_Buy { get; set; }
        public Nullable<decimal> LastMonth_Buy { get; set; }
        public Nullable<decimal> TwoMonthsAgo_Buy { get; set; }
        public Nullable<decimal> ThreeMonthsAgo_Buy { get; set; }
        public Nullable<decimal> CurrentMonth_Hold { get; set; }
        public Nullable<decimal> LastMonth_Hold { get; set; }
        public Nullable<decimal> TwoMonthsAgo_Hold { get; set; }
        public Nullable<decimal> ThreeMonthsAgo_Hold { get; set; }
        public Nullable<decimal> CurrentMonth_Underperform { get; set; }
        public Nullable<decimal> LastMonth_Underperform { get; set; }
        public Nullable<decimal> TwoMonthsAgo_Underperform { get; set; }
        public Nullable<decimal> ThreeMonthsAgo_Underperform { get; set; }
        public Nullable<decimal> CurrentMonth_Sell { get; set; }
        public Nullable<decimal> LastMonth_Sell { get; set; }
        public Nullable<decimal> TwoMonthsAgo_Sell { get; set; }
        public Nullable<decimal> ThreeMonthsAgo_Sell { get; set; }
        public string Group { get; set; }
    }
}
